Bump ansible-lint version
Currently we use a very old version of ansible-lint and there occurs
an error while preparing the pre-commit environment for checks:
```
...
      error: can't copy 'src/ansiblelint/_vendor/ansible_compat': doesn't exist or not a regular file
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ansible-lint
error: failed-wheel-build-for-install
```

That was caused by distribution model and usage of git submodules
that apparently was removed in favor of a regular PyPI dependency [1].

Assisted-by: Claude Sonnet 4.5

[1] https://github.com/ansible/ansible-lint/pull/3478