Add check to EDPM compute DHCP Reservation
Add condition so that `virsh net-update default
add-last ip-dhcp-host` is only run if the MAC
address does not already have an entry.

Running `make edpm_compute_cleanup; make edpm_compute`
more than once on the same hypervisor produces the
error below unless this patch is in place.

+ sudo virsh net-update default add-last ip-dhcp-host \
  --xml '<host mac='\''52:54:00:C1:A3:7F'\'' \
  name='\''edpm-compute-0'\'' ip='\''192.168.122.100'\''/>'\
  --config --live

error: Failed to update network default
error: Requested operation is not valid: there is an
existing dhcp host entry in network 'default' that matches
"<host mac='52:54:00:C1:A3:7F' name='edpm-compute-0'
  ip='192.168.122.100'/>"