Run openstack_repo before make openstack_crds
The openstack_crds rule raises in the CI an error:

    + oc apply -k /home/zuul/src/github.com/openstack-k8s-operators/install_yamls/out/operator/openstack-operator/config/crd --server-side
    error: must build at directory: not a valid directory: evalsymlink failure on '/home/zuul/src/github.com/openstack-k8s-operators/install_yamls/out/operator/openstack-operator/config/crd' : lstat /home/zuul/src/github.com/openstack-k8s-operators/install_yamls/out/operator: no such file or directory
    make: *** [Makefile:1048: openstack_crds] Error 1

Get the required project before executing scripts from openstack_crds.

Co-Authored-By: Enrique Vallespi Gil <evallesp@redhat.com>

Signed-off-by: Daniel Pawlik <dpawlik@redhat.com>